### ISSUE TITLE
SIGABRT occurs when monitor off via dpms

### ISSUE THREAD

**Issue by ghost** [kekekeks/skypetab-ng#70]
1. Run skypetab
2. sleep 1 && xset dpms force off

stdout:
ss@system7$ skypetab-ng 
ERROR: ld.so: object 'libskypetab-ng.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Creating window for skypetab::STabMainWindow
Creating window for skypetab::ContactListContainer
Created main window
Creating window for QWidget
Creating window for Skype::SendContacts
Creating window for Skype::ChatWindow
skype: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
Skype::ChatWindow is under controlAborted (core dumped)

bt:
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib32/skype/skype'.
Program terminated with signal SIGABRT, Aborted.
#0  0xf54e8440 in __kernel_vsyscall ()

(gdb) btE
#0  0xf54e8440 in __kernel_vsyscall ()
#1  0xf27d8cc7 in raise () from /usr/lib32/libc.so.6
#2  0xf27da309 in abort () from /usr/lib32/libc.so.6
#3  0xf624dded in ?? ()
#4  0xf65fd169 in ?? ()
#5  0xf65fd890 in ?? ()
#6  0xf61f1a7c in ?? ()
#7  0xf63e2511 in ?? ()
#8  0xf5b12f6e in ?? ()
#9  0xf2b67deb in QHashData::free_helper(void (_)(QHashData::Node_)) ()

   from /usr/lib32/libQtCore.so.4
#10 0xf5b12cb6 in ?? ()
#11 0xf27db8c3 in __run_exit_handlers () from /usr/lib32/libc.so.6
#12 0xf27db921 in exit () from /usr/lib32/libc.so.6
#13 0xefad5d29 in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#14 0xf5373bfd in _XIOError () from /usr/lib32/libX11.so.6
#15 0xf5371ca9 in _XReply () from /usr/lib32/libX11.so.6
#16 0xf536d2cf in XSync () from /usr/lib32/libX11.so.6
#17 0xf3293782 in QRasterWindowSurface::syncX() ()

   from /usr/lib32/libQtGui.so.4
#18 0xf3293abb in QRasterWindowSurface::beginPaint(QRegion const&) ()

   from /usr/lib32/libQtGui.so.4
#19 0xf32afd20 in ?? () from /usr/lib32/libQtGui.so.4
#20 0xf30b6427 in QWidgetPrivate::syncBackingStore() ()

   from /usr/lib32/libQtGui.so.4
#21 0xf30c8a0e in QWidget::event(QEvent*) () from /usr/lib32/libQtGui.so.4
#22 0xf34e29b2 in QMainWindow::event(QEvent*) ()

   from /usr/lib32/libQtGui.so.4
#23 0xf306dc8a in QApplicationPrivate::notify_helper(QObject_, QEvent_) ()

   from /usr/lib32/libQtGui.so.4
#24 0xf3074ae0 in QApplication::notify(QObject_, QEvent_) ()

   from /usr/lib32/libQtGui.so.4
#25 0xf2c63c8a in QCoreApplication::notifyInternal(QObject_, QEvent_) ()

   from /usr/lib32/libQtCore.so.4
#26 0xf2c67381 in QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData_) () from /usr/lib32/libQtCore.so.4
#27 0xf2c678d5 in QCoreApplication::sendPostedEvents(QObject*, int) ()

---Type <return> to continue, or q <return> to quit---
   from /usr/lib32/libQtCore.so.4
#28 0xf2c95843 in ?? () from /usr/lib32/libQtCore.so.4
#29 0xf25596e4 in g_main_context_dispatch ()

   from /usr/lib32/libglib-2.0.so.0
#30 0xf2559a09 in ?? () from /usr/lib32/libglib-2.0.so.0
#31 0xf2559ad6 in g_main_context_iteration ()

   from /usr/lib32/libglib-2.0.so.0
#32 0xf2c95999 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib32/libQtCore.so.4
#33 0xf311fb56 in ?? () from /usr/lib32/libQtGui.so.4
#34 0xf2c6261f in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib32/libQtCore.so.4
#35 0xf2c629ae in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag)

```
() from /usr/lib32/libQtCore.so.4
```
#36 0xf2c68656 in QCoreApplication::exec() ()

   from /usr/lib32/libQtCore.so.4
#37 0xf306be84 in QApplication::exec() () from /usr/lib32/libQtGui.so.4
#38 0xf57ba87b in ?? ()
#39 0xf27c564e in __libc_start_main () from /usr/lib32/libc.so.6
#40 0xf57ad739 in ?? ()

**Comment by kekekeks** [comment]
I don't see anything skypetab-related in the stack trace. Does vanilla Skype work fine?

**Comment by ghost** [comment]
Yeah, vanilla skype work fine.

**Comment by ava1ar** [comment]
I can confirm the issue.
