### ISSUE TITLE
fedora 22 core dump

### ISSUE THREAD

**Issue by fb929** [kekekeks/skypetab-ng#75]
Hi!
skypetab began core dumped after update system :(
http://www.filedropper.com/core-skype-6-1000-1000-6323-1455632292

**Comment by kekekeks** [comment]
Unfortunately I can't do much about that core dump without actual binaries you are using. Please run `gdb skype <your_core_file>` and type `where`. That should give you a proper backtrace.

**Comment by fb929** [comment]
`gdb skype core-skype-6-1000-1000-6323-1455632292
GNU gdb (GDB) Fedora 7.9.1-20.fc22
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from skype...(no debugging symbols found)...done.
[New LWP 6323]
[New LWP 6329]
[New LWP 6330]
[New LWP 6331]
[New LWP 6334]
[New LWP 6335]
[New LWP 6337]
[New LWP 6333]
[New LWP 6338]
[New LWP 6336]
[New LWP 6339]
[New LWP 6332]
[New LWP 6340]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by`skype'.
Program terminated with signal SIGABRT, Aborted.
#0  0xf778bbf0 in __kernel_vsyscall ()
Missing separate debuginfos, use: dnf debuginfo-install skype-4.3.0.37-fc16.i586
(gdb) where
#0  0xf778bbf0 in __kernel_vsyscall ()
#1  0xf3fab796 in raise () from /lib/libc.so.6
#2  0xf3fad027 in abort () from /lib/libc.so.6
#3  0x572c549d in ?? ()
#4  0xf775a7b0 in QWidget::setVisible(bool) () from /lib/libskypetab-ng.so
#5  0xf4e109b5 in QRubberBand::QRubberBand(QRubberBand::Shape, QWidget_) () from /lib/libQtGui.so.4
#6  0xf4dda434 in QMainWindowLayout::QMainWindowLayout(QMainWindow_, QLayout_) () from /lib/libQtGui.so.4
#7  0xf4dd00ec in QMainWindowPrivate::init() () from /lib/libQtGui.so.4
#8  0xf4dd025c in QMainWindow::QMainWindow(QWidget_, QFlagsQt::WindowType) () from /lib/libQtGui.so.4
#9  0xf77536fb in skypetab::STabMainWindow::STabMainWindow(QWidget_) () from /lib/libskypetab-ng.so
#10 0xf7756d26 in skypetab::SkypeTab::_stage2Init() () from /lib/libskypetab-ng.so
#11 0xf7757494 in skypetab::SkypeTab::stage2Init() () from /lib/libskypetab-ng.so
#12 0xf7757ae5 in skypetab::SkypeTab::onTryShow(QWidget_) () from /lib/libskypetab-ng.so
#13 0xf775a7b0 in QWidget::setVisible(bool) () from /lib/libskypetab-ng.so
#14 0xf4e109b5 in QRubberBand::QRubberBand(QRubberBand::Shape, QWidget_) () from /lib/libQtGui.so.4
#15 0xf4dda434 in QMainWindowLayout::QMainWindowLayout(QMainWindow_, QLayout_) () from /lib/libQtGui.so.4
#16 0xf4dd00ec in QMainWindowPrivate::init() () from /lib/libQtGui.so.4
#17 0xf4dd025c in QMainWindow::QMainWindow(QWidget_, QFlagsQt::WindowType) () from /lib/libQtGui.so.4
#18 0x56904bb3 in ?? ()
#19 0x569064b6 in ?? ()
#20 0x568c1d58 in ?? ()
#21 0xf3f96715 in __libc_start_main () from /lib/libc.so.6
#22 0x568ceabd in ?? ()
(gdb) 
`
